#Vaadin Copilot Integration Runtime Properties
#Thu Apr 09 08:41:34 CEST 2026
endpoint=http\://127.0.0.1\:50238/vaadin/copilot-a66c09a1-0ef2-4317-a143-743299f05cc0
ide=eclipse
supportedActions=write,writeBase64,delete,undo,redo,refresh,showInIde,getModulePaths,compileFiles,restartApplication,getVaadinRoutes,getVaadinVersion,getVaadinComponents,getVaadinEntities,getVaadinSecurity,reloadMavenModule,heartbeat
version=1.0.0
